version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: baby-food-intro
    ports:
      - "5432:5432"
    volumes:
      - /Users/davidalecrim/Workspace/open-source/baby-food-intro-api/db:/var/lib/postgresql/data
