version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: baby-food-intro
    ports:
      - "5432:5432"
    volumes:
      - ${DB_DOCKER_VOLUME_PATH}:/var/lib/postgresql/data
